# Generated by Django 4.0.4 on 2022-05-04 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivision', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Visibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('admin', models.BooleanField()),
                ('blocked', models.BooleanField()),
                ('description', models.CharField(max_length=300)),
                ('access_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidates.access')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidates.branch')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidates.control')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidates.position')),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidates.subdivision')),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidates.branch')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidates.control')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidates.position')),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidates.subdivision')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidateNumber', models.IntegerField()),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('birthday', models.DateField()),
                ('years', models.IntegerField()),
                ('startDay', models.DateField()),
                ('tests', models.BooleanField()),
                ('questionnaire', models.BooleanField()),
                ('hrDecision', models.BooleanField()),
                ('hrAssessmentSheet', models.BooleanField()),
                ('securityDecision', models.BooleanField()),
                ('securityAssessment_sheet', models.BooleanField()),
                ('departmentDecision', models.BooleanField()),
                ('departmentAssessmentSheet', models.BooleanField()),
                ('ceoDecision', models.BooleanField()),
                ('ceoAssessmentSheet', models.BooleanField()),
                ('photo', models.FilePathField()),
                ('ppeSent', models.BooleanField()),
                ('ppeDate', models.DateField()),
                ('ppeSummary', models.BooleanField()),
                ('finalDecision', models.BooleanField()),
                ('finalDate', models.DateField()),
                ('notes', models.TextField()),
                ('remarks', models.TextField()),
                ('candidateStatus', models.BooleanField()),
                ('recruitment', models.BooleanField()),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidates.access')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidates.branch')),
                ('ceo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ceo', to='candidates.specialist')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidates.control')),
                ('departmentSpecialist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departmentSpecialist', to='candidates.specialist')),
                ('hrSpecialist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hrSpecialist', to='candidates.specialist')),
                ('materials', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidates.materials')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidates.position')),
                ('securitySpecialist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='securitySpecialist', to='candidates.specialist')),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidates.subdivision')),
                ('visibility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidates.visibility')),
            ],
        ),
    ]
