# Generated by Django 4.0.4 on 2022-05-05 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='access',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='candidates.access'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidateStatus',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='ceo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='ceo', to='candidates.specialist'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='ceoAssessmentSheet',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='ceoDecision',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='departmentAssessmentSheet',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='departmentDecision',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='departmentSpecialist',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='departmentSpecialist', to='candidates.specialist'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='finalDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='finalDecision',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='hrAssessmentSheet',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='hrDecision',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='hrSpecialist',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='hrSpecialist', to='candidates.specialist'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='materials',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='candidates.materials'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.FilePathField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='ppeDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='ppeSent',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='ppeSummary',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='questionnaire',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='recruitment',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='securityAssessment_sheet',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='securityDecision',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='securitySpecialist',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='securitySpecialist', to='candidates.specialist'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='tests',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='visibility',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='candidates.visibility'),
        ),
    ]
