# Generated by Django 4.0.4 on 2022-05-05 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_candidate_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='access_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='candidates.access'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialist',
            name='admin',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='created',
            field=models.DateField(default='1990-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialist',
            name='description',
            field=models.CharField(default=1, help_text='Коментарии', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialist',
            name='user',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidateNumber',
            field=models.IntegerField(help_text='1234567'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(help_text='mailbox@mail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(help_text='Имя', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='patronymic',
            field=models.CharField(help_text='Отчество', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.IntegerField(help_text='+7 (987) 123-45-67'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='surname',
            field=models.CharField(help_text='Фамилия', max_length=50),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='name',
            field=models.CharField(help_text='Имя', max_length=50),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='patronymic',
            field=models.CharField(help_text='Отчество', max_length=50),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='surname',
            field=models.CharField(help_text='Фамилия', max_length=50),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
