# Generated by Django 4.0.4 on 2022-05-05 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_alter_candidate_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='access',
            field=models.IntegerField(verbose_name='Доступ'),
        ),
        migrations.AlterField(
            model_name='access',
            name='description',
            field=models.CharField(blank=True, help_text='Опасание', max_length=200, null=True, verbose_name='Опасание'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch',
            field=models.CharField(max_length=150, verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='access',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='candidates.access', verbose_name='Доступ'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='birthday',
            field=models.DateField(verbose_name='Рождения'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='branch',
            field=models.ForeignKey(help_text='Выберите филиал', on_delete=django.db.models.deletion.PROTECT, to='candidates.branch', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidateNumber',
            field=models.IntegerField(help_text='1234567', verbose_name='Номер кандидата'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidateStatus',
            field=models.BooleanField(blank=True, null=True, verbose_name='Статус кандидата'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='ceo',
            field=models.ForeignKey(blank=True, help_text='Выберите сотрудника', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ceo', to='candidates.specialist', verbose_name='Генеральный директор/ЗГД'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='ceoAssessmentSheet',
            field=models.BooleanField(blank=True, null=True, verbose_name='Лист оценки ГД/ЗГД'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='ceoDecision',
            field=models.BooleanField(blank=True, null=True, verbose_name='Решение ГД/ЗГД'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='control',
            field=models.ForeignKey(help_text='Выберите управление', on_delete=django.db.models.deletion.PROTECT, to='candidates.control', verbose_name='Управление'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='departmentAssessmentSheet',
            field=models.BooleanField(blank=True, null=True, verbose_name='Лист оценки подразделения'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='departmentDecision',
            field=models.BooleanField(blank=True, null=True, verbose_name='Решение подразделения'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='departmentSpecialist',
            field=models.ForeignKey(blank=True, help_text='Выберите сотрудника', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departmentSpecialist', to='candidates.specialist', verbose_name='Специалист подразделения'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(help_text='mailbox@mail.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='finalDate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата итогового решения'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='finalDecision',
            field=models.BooleanField(blank=True, null=True, verbose_name='Итоговое решение'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='hrAssessmentSheet',
            field=models.BooleanField(blank=True, null=True, verbose_name='Лист оценки УРП'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='hrDecision',
            field=models.BooleanField(blank=True, null=True, verbose_name='Решение УРП'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='hrSpecialist',
            field=models.ForeignKey(blank=True, help_text='Выберите сотрудника', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hrSpecialist', to='candidates.specialist', verbose_name='Специалист УРП'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='materials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='candidates.materials', verbose_name='Материалы'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(help_text='Иван', max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='patronymic',
            field=models.CharField(help_text='Иванович', max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.IntegerField(help_text='+7 (987) 123-45-67', verbose_name='Номер тел.'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.FilePathField(blank=True, help_text='Выберите фотографию', null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.ForeignKey(help_text='Выберите должность', on_delete=django.db.models.deletion.PROTECT, to='candidates.position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='ppeDate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата ПФО'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='ppeSent',
            field=models.BooleanField(blank=True, null=True, verbose_name='Направление на ПФО'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='ppeSummary',
            field=models.BooleanField(blank=True, null=True, verbose_name='Итог ПФО'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='questionnaire',
            field=models.BooleanField(blank=True, null=True, verbose_name='Анкета'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='recruitment',
            field=models.BooleanField(blank=True, null=True, verbose_name='На приём'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Замечания'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='securityAssessment_sheet',
            field=models.BooleanField(blank=True, null=True, verbose_name='Лист оценки СБ'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='securityDecision',
            field=models.BooleanField(blank=True, null=True, verbose_name='Решение СБ'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='securitySpecialist',
            field=models.ForeignKey(blank=True, help_text='Выберите сотрудника', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='securitySpecialist', to='candidates.specialist', verbose_name='Специалист СБ'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='startDay',
            field=models.DateField(verbose_name='Начало работы'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='subdivision',
            field=models.ForeignKey(help_text='Выберите подразделение', on_delete=django.db.models.deletion.PROTECT, to='candidates.subdivision', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='surname',
            field=models.CharField(help_text='Иванов', max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='tests',
            field=models.BooleanField(blank=True, null=True, verbose_name='Тесты'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='visibility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='candidates.visibility', verbose_name='Видимость'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='years',
            field=models.IntegerField(verbose_name='Полных лет'),
        ),
        migrations.AlterField(
            model_name='control',
            name='control',
            field=models.CharField(max_length=150, verbose_name='Управление'),
        ),
        migrations.AlterField(
            model_name='position',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='admin',
            field=models.BooleanField(default='False', verbose_name='Администратор'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='description',
            field=models.CharField(help_text='Коментарии', max_length=300, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='name',
            field=models.CharField(help_text='Иван', max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='patronymic',
            field=models.CharField(help_text='Иванович', max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='surname',
            field=models.CharField(help_text='Иванов', max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='user',
            field=models.BooleanField(default='False', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='subdivision',
            field=models.CharField(max_length=150, verbose_name='Подразделение'),
        ),
    ]
