# Generated by Django 4.0.4 on 2022-05-05 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_alter_access_access_alter_access_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={'verbose_name': 'Уровень доступа', 'verbose_name_plural': 'Уровни доступа'},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Филиал', 'verbose_name_plural': 'Филиалы'},
        ),
        migrations.AlterModelOptions(
            name='candidate',
            options={'verbose_name': 'Кандидат', 'verbose_name_plural': 'Кандидаты'},
        ),
        migrations.AlterModelOptions(
            name='control',
            options={'verbose_name': 'Управление', 'verbose_name_plural': 'Управления'},
        ),
        migrations.AlterModelOptions(
            name='materials',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='specialist',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='subdivision',
            options={'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
        migrations.AlterModelOptions(
            name='visibility',
            options={'verbose_name': 'Локальные права', 'verbose_name_plural': 'Локальные права'},
        ),
        migrations.AlterField(
            model_name='access',
            name='access',
            field=models.IntegerField(verbose_name='Уровень доступа'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='name',
            field=models.CharField(help_text='Имя файла', max_length=100, verbose_name='Имя файла'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='access_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidates.access', verbose_name='Уровень доступа'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='branch',
            field=models.ForeignKey(help_text='Выберите филиал', on_delete=django.db.models.deletion.PROTECT, to='candidates.branch', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='control',
            field=models.ForeignKey(help_text='Выберите управление', on_delete=django.db.models.deletion.PROTECT, to='candidates.control', verbose_name='Управление'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='position',
            field=models.ForeignKey(help_text='Выберите должность', on_delete=django.db.models.deletion.PROTECT, to='candidates.position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='subdivision',
            field=models.ForeignKey(help_text='Выберите подразделение', on_delete=django.db.models.deletion.PROTECT, to='candidates.subdivision', verbose_name='Подразделение'),
        ),
    ]
