# Generated by Django 4.0.4 on 2022-05-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_alter_access_options_alter_branch_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='path',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.CharField(help_text='+7 (987) 123-45-67', max_length=20, verbose_name='Номер тел.'),
        ),
    ]
