# Generated by Django 4.0.4 on 2022-05-12 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_remove_candidate_photo_remove_materials_path_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['position'], 'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='specialist',
            options={'ordering': ['surname'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='candidate',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Выберите филиал', null=True, on_delete=django.db.models.deletion.PROTECT, to='candidates.branch', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidateNumber',
            field=models.IntegerField(blank=True, help_text='1234567', null=True, verbose_name='Номер кандидата'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidateStatus',
            field=models.BooleanField(blank=True, choices=[(True, 'В работе'), (False, 'Завершено')], null=True, verbose_name='Статус кандидата'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='control',
            field=models.ForeignKey(blank=True, help_text='Выберите управление', null=True, on_delete=django.db.models.deletion.PROTECT, to='candidates.control', verbose_name='Управление'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='finalDecision',
            field=models.BooleanField(blank=True, choices=[(True, 'Принять'), (False, 'Отказать')], null=True, verbose_name='Итоговое решение'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='patronymic',
            field=models.CharField(blank=True, help_text='Иванович', max_length=50, null=True, verbose_name='Отчество, если имеется'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.ForeignKey(blank=True, help_text='Выберите должность', null=True, on_delete=django.db.models.deletion.PROTECT, to='candidates.position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='ppeSummary',
            field=models.BooleanField(blank=True, choices=[(True, 'Плюс'), (False, 'Минус')], null=True, verbose_name='Итог ПФО'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='subdivision',
            field=models.ForeignKey(blank=True, help_text='Выберите подразделение', null=True, on_delete=django.db.models.deletion.PROTECT, to='candidates.subdivision', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='years',
            field=models.IntegerField(blank=True, null=True, verbose_name='Полных лет'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='control',
            field=models.ForeignKey(blank=True, help_text='Выберите управление', null=True, on_delete=django.db.models.deletion.PROTECT, to='candidates.control', verbose_name='Управление'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='patronymic',
            field=models.CharField(blank=True, help_text='Иванович', max_length=50, null=True, verbose_name='Отчество, если имеется'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='subdivision',
            field=models.ForeignKey(blank=True, help_text='Выберите подразделение', null=True, on_delete=django.db.models.deletion.PROTECT, to='candidates.subdivision', verbose_name='Подразделение'),
        ),
    ]
