# Generated by Django 4.0.4 on 2022-05-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_alter_position_options_alter_specialist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='controlBr',
            field=models.CharField(default=0, max_length=10, verbose_name='Управление кратко'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidateStatus',
            field=models.BooleanField(blank=True, null=True, verbose_name='Статус кандидата'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(blank=True, help_text='mailbox@mail.com', max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='finalDecision',
            field=models.BooleanField(blank=True, null=True, verbose_name='Итоговое решение'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='ppeSummary',
            field=models.BooleanField(blank=True, null=True, verbose_name='Итог ПФО'),
        ),
    ]
