# Generated by Django 4.0.4 on 2022-05-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_control_controlbr_alter_candidate_candidatestatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdivision',
            name='subdivisionBr',
            field=models.CharField(default=0, max_length=150, verbose_name='Подразделение кратко'),
            preserve_default=False,
        ),
    ]
