# Generated by Django 4.0.4 on 2022-05-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_subdivision_subdivisionbr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='control',
            options={'ordering': ['control'], 'verbose_name': 'Управление', 'verbose_name_plural': 'Управления'},
        ),
        migrations.AlterModelOptions(
            name='subdivision',
            options={'ordering': ['subdivision'], 'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
        migrations.AddField(
            model_name='position',
            name='positionBr',
            field=models.CharField(default=0, max_length=10, verbose_name='Должность кратко'),
            preserve_default=False,
        ),
    ]
