# Generated by Django 4.0.4 on 2022-05-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0012_speciality_alter_candidate_candidatestatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportStatus',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=150, null=True, verbose_name='Филиал')),
                ('control', models.CharField(blank=True, max_length=10, null=True, verbose_name='Управление')),
                ('subdivision', models.CharField(blank=True, max_length=150, null=True, verbose_name='Подразделение')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность')),
                ('candidateName', models.TextField(blank=True, null=True, verbose_name='ФИО Кандидата')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('starDay', models.DateField(verbose_name='Начало работы')),
                ('ppeDate', models.DateField(verbose_name='Дата ПФО')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Примечание')),
            ],
            options={
                'db_table': 'candidates_report',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='speciality',
            options={'ordering': ['speciality'], 'verbose_name': 'Специальность', 'verbose_name_plural': 'Специальности'},
        ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW public.candidates_report
            AS SELECT cc.id,
                ( SELECT cb.branch
                       FROM candidates_branch cb
                      WHERE cb.id = cc.branch_id) AS branch,
                ( SELECT cc2."controlBr"
                       FROM candidates_control cc2
                      WHERE cc2.id = cc.control_id) AS control,
                ( SELECT cs."subdivisionBr"
                       FROM candidates_subdivision cs
                      WHERE cs.id = cc.subdivision_id) AS subdivision,
                ( SELECT cp."position"
                       FROM candidates_position cp
                      WHERE cp.id = cc.position_id) AS "position",
                concat(cc.surname, ' ', cc.name, ' ', cc.patronymic) AS "candidateName",
            --    case 
            --    	when cc.phone is not null 
            --    	then concat('+7 ', '(', substring(cc.phone from 1 for 3), ') ', substring(cc.phone from 4 for 3), '-', substring(cc.phone from 7 for 2), '-', substring(cc.phone from 9 for 2))
            --    	else ''
            --    end as "phone",
                cc.phone,
                cc."startDay",
                cc."ppeDate",
                cc.remarks
               FROM ( SELECT cc1.id,
                        cc1.branch_id,
                        cc1.control_id,
                        cc1.subdivision_id,
                        cc1.position_id,
                        cc1.surname,
                        cc1.name,
                        cc1.patronymic,
                         case 
                    when cc1.phone is not null 
                    then concat('+7 ', '(', substring(cc1.phone from 1 for 3), ') ', substring(cc1.phone from 4 for 3), '-', substring(cc1.phone from 7 for 2), '-', substring(cc1.phone from 9 for 2))
                    else ''
                    end as "phone",
                        cc1."startDay",
                        cc1."ppeDate",
                        cc1.remarks
                       FROM candidates_candidate cc1
                      WHERE cc1."candidateStatus" = false) cc;
            """,
            "DROP VIEW candidates_report;"
        )
    ]
