# Generated by Django 4.0.4 on 2022-05-24 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0013_reportstatus_alter_speciality_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportstatus',
            options={'managed': False, 'verbose_name': 'Отчет "В работе"', 'verbose_name_plural': 'Отчет "В работе"'},
        ),
    ]
